## Analyzing outputs of 5 parameter sets ensemble simulaitons

Analyzing the first batch of ensemble simulations. <br/>
Simulation outputs stored: /home/disk/eos8/ach315/upscale/sims/opt

In [3]:
import dill
dill.load_session('sim_opt5_env.db')

In [1]:
import numpy as np
import pandas as pd
import matplotlib.path as mpath
import matplotlib.pyplot as plt
import glob
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import cartopy.io.shapereader as shpreader
import xarray as xr
import datetime
import seaborn as sns

from scipy.stats.stats import pearsonr
from palettable.colorbrewer.sequential import OrRd_6
from palettable.colorbrewer.sequential import YlGn_9
from palettable.colorbrewer.sequential import YlGnBu_8
from palettable.colorbrewer.sequential import RdPu_5

In [9]:
# manual update of maizsim output column name
cols = ['jday', 'time', 'leaves', 'mature_lvs', 'drop_lvs', 'LA', 'LA_dead', 'LAI', 'RH', 
        'leaf_WP', 'PFD', 'solrad', 'temp_soil', 'temp_air', 'temp_can', 'ET_dmd', 'ET_suply',
        'Pn', 'Pg', 'resp', 'av_gs', 'LAI_sunlit', 'LAI_shaded', 'PFD_sunlit', 'PFD_shaded', 
        'An_sunlit', 'An_shaded', 'Ag_sunlit', 'Ag_shaded', 'gs_sunlit', 'gs_shaded', 'VPD',
        'N', 'N_dmd', 'N_upt', 'N_leaf', 'PCRL', 'dm_total', 'dm_shoot', 'dm_ear', 'dm_totleaf', 'dm_dropleaf', 
        'df_stem', 'df_root', 'roil_rt', 'mx_rootdept', 'available_water', 'soluble_c', 'note']

In [18]:
test = pd.read_csv('/home/disk/eos8/ach315/upscale/sims/opt/1961/var_0/out1_03813_1961_var_0.txt')

In [21]:
test.head()

,date,jday,time,Leaves,MaturLvs,Dropped,LA/pl,LA_dead,LAI,RH,...,earDM,TotleafDM,DrpLfDM,stemDM,rootDM,SoilRt,MxRtDep,AvailW,solubleC,Note
04/01/1961,22372,0,0.0,0,0,0.0,0.0,0.0,71.81,-0.05,...,0.0,0.15,0.0,0.02,0.11,0.0,0.0,0.0,0.0,"""none"""
04/01/1961,22372,1,0.0,0,0,0.0,0.0,0.0,80.33,-0.05,...,0.0,0.15,0.0,0.02,0.11,0.0,0.0,0.0,0.0,"""none"""
04/01/1961,22372,2,0.0,0,0,0.0,0.0,0.0,86.37,-0.05,...,0.0,0.15,0.0,0.02,0.11,0.0,0.0,0.0,0.0,"""none"""
04/01/1961,22372,3,0.0,0,0,0.0,0.0,0.0,86.32,-0.05,...,0.0,0.15,0.0,0.02,0.11,0.0,0.0,0.0,0.0,"""none"""
04/01/1961,22372,4,0.0,0,0,0.0,0.0,0.0,92.90,-0.05,...,0.0,0.15,0.0,0.02,0.11,0.0,0.0,0.0,0.0,"""none"""

In [ ]:
years = np.arange(1961,1991)
cultivars = np.arange(0,5)
yrs = []
cvars = []
sites = []
dm_ears = []


for i in years:
    for j in cultivars:
        sims = glob.glob('/home/disk/eos8/ach315/upscale/sims/opt/' + str(i) + '/var_' + str(j) + '/out1*.txt')
        for sim in sims:
            site = sim.split('/')[-1].split('_')[1]
            df = pd.read_csv(sim)
            df.columns = cols
            ear = df.dm_ear.max()
            yrs.append(i)
            cvars.append(j)
            sites.append(site)
            dm_ears.append(ear)
            
        print(i, j)

In [4]:
dill.dump_session('sim_opt5_env.db')